# Generated by Django 5.1.6 on 2025-12-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_package_payment_status_package_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='package_image',
            field=models.ImageField(blank=True, null=True, upload_to='packages/'),
        ),
        migrations.AddField(
            model_name='package',
            name='verification_code',
            field=models.CharField(default='000000', editable=False, max_length=6),
            preserve_default=False,
        ),
    ]
